package gestionContratsTravail;

import classesMetier.ContratCession;
import classesMetier.ContratTravail;
import classesMetier.Intermittent;
import classesMetier.Representation;
import classesMetier.Spectacle;
import classesMetier.User;
import gestionRepresentations.RepresentationAjouter;
import gestionRepresentations.RepresentationAjouterDansContratCession;
import java.text.DateFormat;
import java.text.DecimalFormat;
import java.text.NumberFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import nezdames.serialisation.NezDamesSerialisation;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import static nezdames.serialisation.NezDamesSerialisation.lesContratsCession;

/**
 *
 * @author MF, AG
 */
public class ContratTravailAjouter extends javax.swing.JFrame {

    public ContratTravailAjouter() {
        initComponents();

        //pour que toute l'application ne se ferme pas quand on clique sur la croix rouge
        this.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);

        //on remplit la combobox intermittents
        jComboBoxNom.removeAllItems();
        for (Intermittent unIntermittent : NezDamesSerialisation.lesIntermittents) {
            jComboBoxNom.addItem(unIntermittent.getNomIntermittent() +" "+unIntermittent.getPrenomIntermittent());
        }

        jComboBoxCCE.removeAllItems();
        //On remplit la Jcombobox pour contrat de cession
        for (ContratCession unContratCession : lesContratsCession) {
            jComboBoxCCE.addItem(unContratCession.getNumeroContratCession());
        }

        //on remplit la JComboBox
        jComboBoxRole.removeAllItems();

        ArrayList<String> lesRoles = new ArrayList();

        lesRoles.add("Artiste");
        lesRoles.add("Costumier / Costumière");
        lesRoles.add("Metteur en scène");
        lesRoles.add("Technicien");
        lesRoles.add("Animateur");

        for (String unRole : lesRoles) {
            jComboBoxRole.addItem(unRole);
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblTitre3 = new javax.swing.JLabel();
        btnEnvoyer = new javax.swing.JButton();
        btnAnnuler = new javax.swing.JButton();
        lblRole = new javax.swing.JLabel();
        jComboBoxRole = new javax.swing.JComboBox();
        lblImageManu = new javax.swing.JLabel();
        lblImageOlivier = new javax.swing.JLabel();
        lblNbrHeure = new javax.swing.JLabel();
        txtNbrHeure = new javax.swing.JTextField();
        lblEditer = new javax.swing.JLabel();
        txtEditer = new javax.swing.JTextField();
        lblJours = new javax.swing.JLabel();
        txtJours = new javax.swing.JTextField();
        lblCCE = new javax.swing.JLabel();
        jComboBoxCCE = new javax.swing.JComboBox();
        lblNomInter = new javax.swing.JLabel();
        lblDateHeure = new javax.swing.JLabel();
        jComboBoxDate = new javax.swing.JComboBox();
        jComboBoxNom = new javax.swing.JComboBox();
        jComboBoxNumeroRepresentation = new javax.swing.JComboBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(204, 204, 204));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setForeground(new java.awt.Color(255, 153, 51));

        lblTitre3.setFont(new java.awt.Font("Hannotate SC", 1, 18)); // NOI18N
        lblTitre3.setForeground(new java.awt.Color(255, 153, 0));
        lblTitre3.setText("CRÉATION D'UN CONTRAT DE TRAVAIL");

        btnEnvoyer.setFont(new java.awt.Font("Hannotate SC", 0, 13)); // NOI18N
        btnEnvoyer.setText("Créer le contrat ");
        btnEnvoyer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEnvoyerActionPerformed(evt);
            }
        });

        btnAnnuler.setFont(new java.awt.Font("Hannotate SC", 0, 13)); // NOI18N
        btnAnnuler.setText("Annuler");
        btnAnnuler.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAnnulerActionPerformed(evt);
            }
        });

        lblRole.setFont(new java.awt.Font("Hannotate SC", 0, 13)); // NOI18N
        lblRole.setForeground(new java.awt.Color(255, 153, 51));
        lblRole.setText("Rôle");

        jComboBoxRole.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxRoleActionPerformed(evt);
            }
        });

        lblImageManu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/portraitManu.png"))); // NOI18N

        lblImageOlivier.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/portraitOlivier.png"))); // NOI18N

        lblNbrHeure.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        lblNbrHeure.setForeground(new java.awt.Color(255, 153, 0));
        lblNbrHeure.setText("Nombre d'heures");

        lblEditer.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        lblEditer.setForeground(new java.awt.Color(255, 153, 0));
        lblEditer.setText("Souhaiteriez-vous l'éditer plus tard ?");

        lblJours.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        lblJours.setForeground(new java.awt.Color(255, 153, 0));
        lblJours.setText("Quels Jours y allez-vous ?");

        txtJours.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txtJours.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtJoursActionPerformed(evt);
            }
        });

        lblCCE.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        lblCCE.setForeground(new java.awt.Color(255, 153, 0));
        lblCCE.setText("Contrat de Cession Editer");

        jComboBoxCCE.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBoxCCE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxCCEActionPerformed(evt);
            }
        });

        lblNomInter.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        lblNomInter.setForeground(new java.awt.Color(255, 153, 0));
        lblNomInter.setText("Nom et prénom de l'intermittent");

        lblDateHeure.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        lblDateHeure.setForeground(new java.awt.Color(255, 153, 0));
        lblDateHeure.setText("Date et heure de la représentation");

        jComboBoxDate.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jComboBoxNom.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jComboBoxNumeroRepresentation.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBoxNumeroRepresentation.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentHidden(java.awt.event.ComponentEvent evt) {
                jComboBoxNumeroRepresentationComponentHidden(evt);
            }
        });
        jComboBoxNumeroRepresentation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxNumeroRepresentationActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblImageManu)
                        .addGap(24, 24, 24)
                        .addComponent(lblTitre3)
                        .addGap(18, 18, 18)
                        .addComponent(lblImageOlivier))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(61, 61, 61)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblNomInter)
                            .addComponent(btnEnvoyer)
                            .addComponent(lblEditer)
                            .addComponent(lblNbrHeure)
                            .addComponent(lblRole)
                            .addComponent(lblDateHeure)
                            .addComponent(lblJours)
                            .addComponent(lblCCE))
                        .addGap(33, 33, 33)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jComboBoxRole, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtNbrHeure, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtJours)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jComboBoxDate, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(27, 27, 27)
                                .addComponent(jComboBoxNumeroRepresentation, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(btnAnnuler)
                            .addComponent(txtEditer, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jComboBoxCCE, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jComboBoxNom, javax.swing.GroupLayout.PREFERRED_SIZE, 328, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(26, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(56, 56, 56)
                        .addComponent(lblTitre3))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblImageManu))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblImageOlivier)))
                .addGap(24, 24, 24)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNomInter)
                    .addComponent(jComboBoxNom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCCE)
                    .addComponent(jComboBoxCCE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBoxDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblDateHeure)
                    .addComponent(jComboBoxNumeroRepresentation, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBoxRole, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblRole))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtEditer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblEditer))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNbrHeure, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblNbrHeure))
                .addGap(52, 52, 52)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtJours, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblJours))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAnnuler)
                    .addComponent(btnEnvoyer))
                .addContainerGap(39, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(705, 673));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnEnvoyerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEnvoyerActionPerformed

        //--------------CREATION DU CONTRAT DE TRAVAIL-------------------------------------
        
        //on remplit la combobox intermittents
        Intermittent cetIntermittent = null;
        //jComboBoxNom.removeAllItems();
        
        String chaine = null;
        String nomPrenomChoisi = null;
        
        for (Intermittent unIntermittent : NezDamesSerialisation.lesIntermittents) {
            chaine = unIntermittent.getNomIntermittent()+" "+unIntermittent.getPrenomIntermittent();
            nomPrenomChoisi=jComboBoxNom.getSelectedItem().toString();
            if(chaine.compareTo(nomPrenomChoisi) == 0){
            cetIntermittent = unIntermittent;
            }
        }
        
         // test qui vérifie que les champs sont remplis
        /*if (txtNbrHeure.getText().compareTo("") == 0) {
            JOptionPane.showMessageDialog(null, "Il faut saisir le nombre d'heures travailler");
        }
        else if (txtJours.getText().compareTo("") == 0) {
            JOptionPane.showMessageDialog(null, "Il faut saisir les jours ou vous travaillez");
        }
        else if (txtEditer.getText().compareTo("") == 0) {
            JOptionPane.showMessageDialog(null, "Ecrivez oui ou non");
        } else {*/

            // recherche du Role
            ContratTravail theRole = null;
            for (ContratTravail unContratTravail : NezDamesSerialisation.lesContratsTravail) {
                if (unContratTravail.getRole().compareTo((String) jComboBoxRole.getSelectedItem()) == 0) {
                    theRole = unContratTravail;
                }
            }
            
        ContratCession contratChoisi = null;
        //recherche du contrat de cession
        if (jComboBoxCCE.getItemCount() != 0) {
            for (ContratCession unContratCession : lesContratsCession) {
                if (jComboBoxCCE.getSelectedItem().toString().compareTo(unContratCession.getNumeroContratCession()) == 0) {
                    contratChoisi = unContratCession;
                }
            }
        }

            //------- Début de la construction du numero de contrat de travail
            //on récupère l'année courante
            DateFormat format = new SimpleDateFormat("yy");
            //on récupère la date courante
            Date date = new Date();
            //on formate cette date pour ne récupérer que l'année
            String annee = format.format(date);

            //on récupère le dernier numéro de contrat donné pour cette année et ce type
            int max = 0;
            for (ContratTravail unContratTravail : NezDamesSerialisation.lesContratsTravail) {
                //on regarde si ce contrat est pour cette année et ce type
                if (unContratTravail.getNumContratTravail().substring(0, 2).compareTo(annee) == 0) {
                    int numero = Integer.parseInt(unContratTravail.getNumContratTravail().substring(6));
                    if (numero > max) {
                        max = numero;
                    }
                }
            }
            max++;
            //on formate sur 3 positions l'incrément du numéro de contrat de production
            NumberFormat formatter = new DecimalFormat("000");
            String numeroIncremental = formatter.format(max);
            //on reconstitue le numéro de contrat
            String nouveauNumeroContrat = annee.concat("CTRA").concat(numeroIncremental);
                    //------- Fin de la construction du numero de contrat de Travail

            NezDamesSerialisation.lesContratsTravail.add(new ContratTravail(nouveauNumeroContrat, 
             jComboBoxRole.getSelectedItem().toString(), Integer.parseInt(txtNbrHeure.getText()), 
                    Boolean.parseBoolean(txtEditer.getText()), contratChoisi, cetIntermittent));
             JOptionPane.showMessageDialog(null, "Contrat de Travail ajouté.");
            
            /*User unUser = new User("aa@hotmail.fr", "0003");
            User deUser = new User("bb@hotmail.fr", "0004");
            
            Intermittent unIntermittent = new Intermittent("aa", "aa", "15 aa", "champs", 77420, "aa@hotmail.fr", "0102030405", "02/03/96", "aa", "aaa", "1", "1", "rien", unUser);
            Intermittent deIntermittent = new Intermittent("bb", "b", "15 bb", "champs", 77420, "bb@hotmail.fr", "0504030201", "04/05/93", "bb", "bbb", "1", "1", "rien", deUser);
            
            ArrayList<Intermittent> testIntermittent = new ArrayList<Intermittent>();
            testIntermittent.add(unIntermittent);
            testIntermittent.add(deIntermittent);
            
            Spectacle s1 = new Spectacle("20", 90, "Poule", 2010, 10, "no", "no", testIntermittent);
            
            ContratCession lecontrat = new ContratCession("16CCES001", 2000, s1);
            
            NezDamesSerialisation.lesContratsTravail.add(new ContratTravail("16CTRA001", 
             "Costumière", 35, 
                    true, lecontrat, cetIntermittent));
             JOptionPane.showMessageDialog(null, "Contrat de Travail ajouté.");*/
            
            this.dispose();

        //}
    }//GEN-LAST:event_btnEnvoyerActionPerformed

    private void btnAnnulerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAnnulerActionPerformed
        // fermeture de la fenêtre SaisieMenu
        this.dispose();
    }//GEN-LAST:event_btnAnnulerActionPerformed

    private void jComboBoxRoleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxRoleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxRoleActionPerformed

    private void txtJoursActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtJoursActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtJoursActionPerformed

    private void jComboBoxCCEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxCCEActionPerformed
        jComboBoxDate.removeAllItems();
        jComboBoxNumeroRepresentation.removeAllItems();
        ContratCession contratChoisi = null;
        //recherche du contrat de cession
        if (jComboBoxCCE.getItemCount() != 0) {
            for (ContratCession unContratCession : lesContratsCession) {
                if (jComboBoxCCE.getSelectedItem().toString().compareTo(unContratCession.getNumeroContratCession()) == 0) {
                    contratChoisi = unContratCession;
                }
            }
         //on remplit la jcombobox date
            //Date et Heure Représentation
            if (contratChoisi.getLesRepresentations().size() != 0) {
                for (Representation uneRepresentation : contratChoisi.getLesRepresentations()) {
                    jComboBoxDate.addItem(uneRepresentation.getDate() + " " + uneRepresentation.getHeureDebut() + " " + uneRepresentation.getLeLieu().getNom());
                    jComboBoxNumeroRepresentation.addItem(uneRepresentation.getIdRepresentation());
                }
            }
        }

    }//GEN-LAST:event_jComboBoxCCEActionPerformed

    private void jComboBoxNumeroRepresentationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxNumeroRepresentationActionPerformed
        jComboBoxNumeroRepresentation.setVisible(false);
    }//GEN-LAST:event_jComboBoxNumeroRepresentationActionPerformed

    private void jComboBoxNumeroRepresentationComponentHidden(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_jComboBoxNumeroRepresentationComponentHidden
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxNumeroRepresentationComponentHidden

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ContratTravailAjouter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ContratTravailAjouter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ContratTravailAjouter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ContratTravailAjouter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ContratTravailAjouter().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAnnuler;
    private javax.swing.JButton btnEnvoyer;
    private javax.swing.JComboBox jComboBoxCCE;
    private javax.swing.JComboBox jComboBoxDate;
    private javax.swing.JComboBox jComboBoxNom;
    private javax.swing.JComboBox jComboBoxNumeroRepresentation;
    private javax.swing.JComboBox jComboBoxRole;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblCCE;
    private javax.swing.JLabel lblDateHeure;
    private javax.swing.JLabel lblEditer;
    private javax.swing.JLabel lblImageManu;
    private javax.swing.JLabel lblImageOlivier;
    private javax.swing.JLabel lblJours;
    private javax.swing.JLabel lblNbrHeure;
    private javax.swing.JLabel lblNomInter;
    private javax.swing.JLabel lblRole;
    private javax.swing.JLabel lblTitre3;
    private javax.swing.JTextField txtEditer;
    private javax.swing.JTextField txtJours;
    private javax.swing.JTextField txtNbrHeure;
    // End of variables declaration//GEN-END:variables
}
